# Use custom format:
format="┌ $directory$git_branch$git_status\n└ $character"
palette = 'base16'
add_newline = false

# Prompt symbols 
[character]
# success_symbol = "[🞈](fg:base03)"
# error_symbol = "[🞈](base08)"
# vicmd_symbol = "[🞈](fg:yellow)"
success_symbol = "[>>>](fg:base10)"
error_symbol = "[>>>](fg:base08)"
vicmd_symbol = "[<<<](fg:base09)"

[directory]
format = "[$read_only]($read_only_style)[$path](base13)"
truncation_length = 4
home_symbol= "~"
read_only="󰌾 "
read_only_style="base08"

[git_branch]
format = " [ $branch](base10) "

[git_status]
format = '([\[$ahead_behind$untracked$staged\]]($style) )'
style = "base04"
ahead = 'a$count'
diverged = 'a$ahead_count b$behind_count'
behind = 'b$count'
untracked = "u$count"
staged = "+$count"

# Start flavours
# base16 Dracula Darker colorscheme for starship
# Author: Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)
[palettes.base16]
base00 = '#000000'
base01 = '#121212'
base02 = '#222222'
base03 = '#333333'
base04 = '#999999'
base05 = '#c1c1c1'
base06 = '#dedede'
base07 = '#efefef'
base08 = '#de5daf'
base09 = '#a676b5'
base10 = '#2dca70'
base11 = '#dbe6a0'
base12 = '#b1dfd8'
base13 = '#8ab8c0'
base14 = '#a676b5'
base15 = '#589f76'
# End flavours
