# Use custom format:
format="┌ $directory$git_branch$git_status\n└ $character"
palette = 'base16'
add_newline = false

# Prompt symbols 
[character]
# success_symbol = "[🞈](fg:base03)"
# error_symbol = "[🞈](base08)"
# vicmd_symbol = "[🞈](fg:yellow)"
success_symbol = "[>>>](fg:base10)"
error_symbol = "[>>>](fg:base08)"
vicmd_symbol = "[<<<](fg:base09)"

[directory]
format = "[$read_only]($read_only_style)[$path](base13)"
truncation_length = 4
home_symbol= "~"
read_only="󰌾 "
read_only_style="base08"

[git_branch]
format = " [ $branch](base10) "

[git_status]
format = '([\[$ahead_behind$untracked$staged\]]($style) )'
style = "base04"
ahead = 'a$count'
diverged = 'a$ahead_count b$behind_count'
behind = 'b$count'
untracked = "u$count"
staged = "+$count"

# Start flavours
# base16 Mountain Darker colorscheme for starship
# Author: gnsfujiwara (https://github.com/gnsfujiwara)
[palettes.base16]
base00 = '#000000'
base01 = '#0f0f0f'
base02 = '#121212'
base03 = '#222222'
base04 = '#333333'
base05 = '#cacaca'
base06 = '#e7e7e7'
base07 = '#f0f0f0'
base08 = '#ac8a8c'
base09 = '#b99c95'
base10 = '#aca98a'
base11 = '#8aac8b'
base12 = '#8aabac'
base13 = '#8f8aac'
base14 = '#ac8aac'
base15 = '#ac8a8c'
# End flavours
