# Use custom format:
format="┌ $directory$git_branch$git_status\n└ $character"
palette = 'base16'
add_newline = false

# Prompt symbols 
[character]
# success_symbol = "[🞈](fg:base03)"
# error_symbol = "[🞈](base08)"
# vicmd_symbol = "[🞈](fg:yellow)"
success_symbol = "[>>>](fg:base10)"
error_symbol = "[>>>](fg:base08)"
vicmd_symbol = "[<<<](fg:base09)"

[directory]
format = "[$read_only]($read_only_style)[$path](base13)"
truncation_length = 4
home_symbol= "~"
read_only="󰌾 "
read_only_style="base08"

[git_branch]
format = " [ $branch](base10) "

[git_status]
format = '([\[$ahead_behind$untracked$staged\]]($style) )'
style = "base04"
ahead = 'a$count'
diverged = 'a$ahead_count b$behind_count'
behind = 'b$count'
untracked = "u$count"
staged = "+$count"

# Start flavours
# base16 Sakura Stardust colorscheme for starship
# Author: Stardust-kyun (https://github.com/Stardust-kyun/dotfiles)
[palettes.base16]
base00 = '#000000'
base01 = '#121212'
base02 = '#222222'
base03 = '#333333'
base04 = '#505754'
base05 = '#c1c1c1'
base06 = '#dedede'
base07 = '#eaeaea'
base08 = '#824655'
base09 = '#8f534d'
base10 = '#827d50'
base11 = '#468264'
base12 = '#327d7d'
base13 = '#326482'
base14 = '#645078'
base15 = '#785d50'
# End flavours
